# Generated by Django 4.0.2 on 2022-04-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drwNo', models.PositiveIntegerField(unique=True)),
                ('drwNoDate', models.DateTimeField()),
                ('totSellamnt', models.BigIntegerField()),
                ('firstWinamnt', models.BigIntegerField()),
                ('firstPrzwnerCo', models.PositiveIntegerField()),
                ('drwtNo1', models.PositiveIntegerField()),
                ('drwtNo2', models.PositiveIntegerField()),
                ('drwtNo3', models.PositiveIntegerField()),
                ('drwtNo4', models.PositiveIntegerField()),
                ('drwtNo5', models.PositiveIntegerField()),
                ('drwtNo6', models.PositiveIntegerField()),
                ('bnusNo', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'numbers',
            },
        ),
    ]
